### ISSUE TITLE
Myfirebase failed to download repo

### ISSUE THREAD

**Issue by souhailmerroun** [myfirebase/myfirebase-cli#1]
When I try to create a new component using the CLI, I get the following error.

"Failed to download repo : Path contains invalid characters: C:\Users\souha\www\my-project\new:component\build"

I think it is because my project is named "my-project" & I'm on Windows?  

![2017-10-09_17-24-47](https://user-images.githubusercontent.com/8895242/31348222-d2b5c2d0-ad16-11e7-9fb7-7c4b0feb9bdf.png)

**Comment by amranidev** [comment]
@souhailmerroun 
which Myfirebase-CLI version do you have ???

**Comment by souhailmerroun** [comment]
I have myfirebase-cli@0.1.11

**Comment by amranidev** [comment]
As you may know, this project is still in dev stage :smile: 
the current version is myfirebase-cli@0.1.12
run : `npm update myfirebase-cli -g`
